name: ctrl-crash
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - accelerate==0.30.0
    - diffusers==0.27.2
    - einops==0.8.1
    - lpips==0.1.4
    - matplotlib==3.5.3
    - numpy==2.2.6
    - opencv_python==4.11.0.86
    - packaging==25.0
    - peft==0.10.0
    - Pillow==11.2.1
    - pyquaternion==0.9.9
    - Requests==2.32.3
    - sam2
    - scenedetect==0.6.6
    - scipy==1.15.3
    - Shapely==1.8.5.post1
    - scikit-image==0.24.0
    - torch==2.4.1
    - torchvision
    - tqdm==4.66.5
    - transformers==4.49.0
    - ultralytics==8.3.61
    - videojedi==1.1.0
    - wandb==0.19.11
    - xformers